/*
 * The Compukter Kraft Developers
 *
 * Copyright (C) 2026 Vsevolod Petrov (lazyhat)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.nio.file.Path
import kotlin.io.path.readText

class K16FontTableGeneratorTest {
    @Test
    fun generatesRustTableFromK16FontSource() {
        val source = Path.of("..", "assets", "k16", "fonts", "k16-mono-5x7.font").readText()

        val generated = K16FontTableGenerator().generate(source)

        assertTrue(generated.rustSource.contains("pub fn mono5x7_glyph(ch: char) -> u64"))
        assertTrue(generated.rustSource.contains("'\\u{41}' =>"))
        assertTrue(generated.rustSource.contains("'\\u{2500}' =>"))
        assertFalse(generated.rustSource.contains("GeneratedTerminalFont"))
    }

    @Test
    fun generatorDefinesGuestRustFontTableOutput() {
        val generatorSource = Path.of("src", "main", "kotlin", "K16FontTableGenerator.kt").readText()
        val taskSource = Path.of("src", "main", "kotlin", "GenerateK16FontTablesTask.kt").readText()
        val rootBuild = Path.of("..", "build.gradle.kts").readText()

        assertTrue(generatorSource.contains("guestRustSource"))
        assertTrue(generatorSource.contains("renderGuestRust"))
        assertTrue(generatorSource.contains("MONO5X7_ROWS"))
        assertTrue(taskSource.contains("guestRustOutput"))
        assertTrue(rootBuild.contains("rust/guest/k16-kernel/src/generated/font_mono5x7.rs"))
    }

    @Test
    fun generatesMarkdownSpecimenFromK16FontSource() {
        val source = Path.of("..", "assets", "k16", "fonts", "k16-mono-5x7.font").readText()

        val generated = K16FontTableGenerator().generate(source)

        assertTrue(generated.markdownSpecimen.contains("# K16 Mono 5x7 Font Specimen"))
        assertTrue(generated.markdownSpecimen.contains("- Glyph size: 5x7"))
        assertTrue(generated.markdownSpecimen.contains("## U+0041 A"))
        assertTrue(generated.markdownSpecimen.contains("```text\n.###.\n#...#"))
        assertTrue(generated.markdownSpecimen.contains("## U+2500 ─"))
    }

    @Test
    fun generatedFontArtifactsUseK16Branding() {
        val source = Path.of("..", "assets", "k16", "fonts", "k16-mono-5x7.font").readText()

        val generated = K16FontTableGenerator().generate(source)

        assertTrue(generated.rustSource.contains("Generated by ./gradlew generateK16FontTables"))
        assertTrue(generated.markdownSpecimen.contains("# K16 Mono 5x7 Font Specimen"))
        assertTrue(generated.markdownSpecimen.contains("Source: assets/k16/fonts/k16-mono-5x7.font"))
        assertFalse(generated.rustSource.contains("generateRuxFontTables"))
        assertFalse(generated.markdownSpecimen.contains("Rux Mono"))
        assertFalse(generated.markdownSpecimen.contains("assets/rux/fonts/rux-mono-5x7.font"))
    }

    @Test
    fun fontTableGenerationDoesNotEmitHostKotlinGlyphTables() {
        val generatorSource = Path.of("src", "main", "kotlin", "K16FontTableGenerator.kt").readText()
        val taskSource = Path.of("src", "main", "kotlin", "GenerateK16FontTablesTask.kt").readText()

        assertFalse(generatorSource.contains("kotlinSource"))
        assertFalse(generatorSource.contains("renderKotlin"))
        assertFalse(taskSource.contains("kotlinOutput"))
    }

    @Test
    fun rejectsRowsWithInvalidWidth() {
        val source =
            Path.of("..", "assets", "k16", "fonts", "k16-mono-5x7.font")
                .readText()
                .replaceFirst(".....", "....")

        val error =
            assertThrows(IllegalArgumentException::class.java) {
                K16FontTableGenerator().generate(source)
            }

        assertTrue((error.message ?: "").contains("must be 5 cells"))
    }
}
