/*
 * The Compukter Kraft Developers
 *
 * Copyright (C) 2026 Vsevolod Petrov (lazyhat)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.nio.file.Path
import kotlin.io.path.readText

class K16FontTableGeneratorTest {
    @Test
    fun generatesRustTableFromHeaderDrivenK16FontSource() {
        val source = fontSource()

        val generated = K16FontTableGenerator().generate(source)

        assertTrue(generated.rustSource.contains("pub const GLYPH_WIDTH: i32 = 6;"))
        assertTrue(generated.rustSource.contains("pub const GLYPH_HEIGHT: i32 = 8;"))
        assertTrue(generated.rustSource.contains("pub const CELL_WIDTH: i32 = 6;"))
        assertTrue(generated.rustSource.contains("pub const CELL_HEIGHT: i32 = 9;"))
        assertTrue(generated.rustSource.contains("pub const GLYPH_X: i32 = 0;"))
        assertTrue(generated.rustSource.contains("pub const GLYPH_Y: i32 = 0;"))
        assertTrue(generated.rustSource.contains("pub fn terminal_font_glyph(ch: char) -> u64"))
        assertTrue(generated.rustSource.contains("'\\u{41}' =>"))
        assertTrue(generated.rustSource.contains("'\\u{2500}' =>"))
        assertFalse(generated.rustSource.contains("mono5x7"))
        assertFalse(generated.rustSource.contains("GeneratedTerminalFont"))
    }

    @Test
    fun generatorDefinesGuestRustFontTableOutput() {
        val generatorSource = Path.of("src", "main", "kotlin", "K16FontTableGenerator.kt").readText()
        val taskSource = Path.of("src", "main", "kotlin", "GenerateK16FontTablesTask.kt").readText()
        val rootBuild = Path.of("..", "build.gradle.kts").readText()

        assertTrue(generatorSource.contains("guestRustSource"))
        assertTrue(generatorSource.contains("renderGuestRust"))
        assertTrue(generatorSource.contains("TERMINAL_FONT_ROWS"))
        assertTrue(generatorSource.contains("GLYPH_X"))
        assertTrue(generatorSource.contains("GLYPH_Y"))
        assertTrue(generatorSource.contains("[[u8; GLYPH_HEIGHT]; 128]"))
        assertTrue(taskSource.contains("guestRustOutput"))
        assertTrue(rootBuild.contains("guest/kraftos/kernel/src/generated/terminal_font.rs"))
    }

    @Test
    fun generatesMarkdownSpecimenFromK16FontSource() {
        val source = fontSource()

        val generated = K16FontTableGenerator().generate(source)

        assertTrue(generated.markdownSpecimen.contains("# K16 Terminal Font Specimen"))
        assertTrue(generated.markdownSpecimen.contains("- Glyph size: 6x8"))
        assertTrue(generated.markdownSpecimen.contains("- Cell size: 6x9"))
        assertTrue(generated.markdownSpecimen.contains("- Glyph origin: 0,0"))
        assertTrue(generated.markdownSpecimen.contains("## U+0041 A"))
        assertTrue(generated.markdownSpecimen.contains("```text\n.###..\n#...#."))
        assertTrue(generated.markdownSpecimen.contains("## U+2500 ─"))
    }

    @Test
    fun generatedFontArtifactsUseK16Branding() {
        val source = fontSource()

        val generated = K16FontTableGenerator().generate(source)

        assertTrue(generated.rustSource.contains("Generated by ./gradlew generateK16FontTables"))
        assertTrue(generated.markdownSpecimen.contains("# K16 Terminal Font Specimen"))
        assertTrue(generated.markdownSpecimen.contains("Source: assets/k16/fonts/k16-terminal.font"))
        assertFalse(generated.rustSource.contains("generateRuxFontTables"))
        assertFalse(generated.markdownSpecimen.contains("Rux Mono"))
        assertFalse(generated.markdownSpecimen.contains("assets/rux/fonts/rux-mono-5x7.font"))
    }

    @Test
    fun lowercaseGlyphsReserveBottomRowForDescenders() {
        val source = fontSource()
        K16FontTableGenerator().generate(source)

        for (ch in "abcdehimnorsuvwxz") {
            assertEquals(
                "......",
                glyphRows(source, ch).last(),
                "lowercase `$ch` should not use the descender row",
            )
        }
        for (ch in "gjpqy") {
            assertTrue(
                glyphRows(source, ch).last().contains('#'),
                "lowercase `$ch` should use the descender row",
            )
        }
    }

    @Test
    fun fontTableGenerationDoesNotEmitHostKotlinGlyphTables() {
        val generatorSource = Path.of("src", "main", "kotlin", "K16FontTableGenerator.kt").readText()
        val taskSource = Path.of("src", "main", "kotlin", "GenerateK16FontTablesTask.kt").readText()

        assertFalse(generatorSource.contains("kotlinSource"))
        assertFalse(generatorSource.contains("renderKotlin"))
        assertFalse(taskSource.contains("kotlinOutput"))
    }

    @Test
    fun rejectsRowsWithInvalidWidth() {
        val source =
            fontSource()
                .replaceFirst(".....", "....")

        val error =
            assertThrows(IllegalArgumentException::class.java) {
                K16FontTableGenerator().generate(source)
            }

        assertTrue((error.message ?: "").contains("must be 6 cells"))
    }

    @Test
    fun rejectsGlyphPlacementOutsideCell() {
        val source =
            fontSource()
                .replaceFirst("glyph_y 0", "glyph_y 2")

        val error =
            assertThrows(IllegalArgumentException::class.java) {
                K16FontTableGenerator().generate(source)
            }

        assertTrue((error.message ?: "").contains("glyph placement must fit inside cell"))
    }

    private fun fontSource(): String = Path.of("..", "assets", "k16", "fonts", "k16-terminal.font").readText()

    private fun glyphRows(
        source: String,
        ch: Char,
    ): List<String> {
        val header = "glyph U+${ch.code.toString(radix = 16).uppercase().padStart(4, '0')}"
        val lines = source.lines()
        val index = lines.indexOfFirst { it.startsWith(header) }
        require(index >= 0) { "missing glyph header for `$ch`" }
        return lines.drop(index + 1).take(8)
    }
}
