#!/usr/bin/env sh
#
# The Compukter Kraft Developers
#
# Copyright (C) 2026 Vsevolod Petrov (lazyhat)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
MANIFEST="$ROOT/native/rux-compiler/Cargo.toml"

usage() {
    cat >&2 <<'EOF'
usage:
  rux emit <input.rx> <output.ruxi>
  rux disasm <input.ruxi>
EOF
}

if [ "$#" -lt 1 ]; then
    usage
    exit 2
fi

COMMAND=$1
shift

case "$COMMAND" in
    emit)
        exec cargo run --quiet --manifest-path "$MANIFEST" --bin rux-emit -- "$@"
        ;;
    disasm|disassemble)
        exec cargo run --quiet --manifest-path "$MANIFEST" --bin rux-disasm -- "$@"
        ;;
    *)
        usage
        exit 2
        ;;
esac
