modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0"

[[mods]]
modId="compukters_propulsion"
version="${addon_version}"
displayName="Compukters: Propulsion"
authors="lazyhat"
description="Creative Thruster control adapter for Compukters."

[[dependencies.compukters_propulsion]]
modId="neoforge"
type="required"
versionRange="[21.1.252,)"
ordering="NONE"
side="BOTH"

[[dependencies.compukters_propulsion]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.compukters_propulsion]]
modId="compukters"
type="required"
versionRange="[0.5.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.compukters_propulsion]]
modId="createpropulsion"
type="required"
versionRange="[1.1.5]"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="compukters_propulsion.mixins.json"

[[dependencies.compukters_propulsion]]
modId="create"
type="required"
versionRange="[6.0.10,6.1)"
ordering="AFTER"
side="BOTH"
