#ifndef KRAFT_SDK_FS_H
#define KRAFT_SDK_FS_H

#define KRAFT_ERROR_READ_ONLY (-30)
#define KRAFT_MAX_PATH_BYTES 228u
#define KRAFT_RENAME_REQUEST_MAGIC 0x4d414e52u
#define KRAFT_MAX_RENAME_REQUEST_BYTES (12u + KRAFT_MAX_PATH_BYTES * 2u)

#endif
