/*
 * The Compukter Kraft Developers
 *
 * Copyright (C) 2026 Vsevolod Petrov (lazyhat)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package ru.lazyhat.compukterkraft.impl.computer.vm

import ru.lazyhat.compukterkraft.core.device.runtime.RuntimeHostCallMetrics
import ru.lazyhat.compukterkraft.core.device.runtime.RuntimeProfilingSnapshot
import ru.lazyhat.compukterkraft.core.device.vm.display.DisplayProfilingSnapshot
import ru.lazyhat.compukterkraft.lang.frontend.CompilerProfilingSnapshot

internal data class VmRunnerProfile(
    val runnerName: String,
    val workloads: List<RuntimeWorkloadProfile>,
)

internal data class RuntimeWorkloadProfile(
    val name: String,
    val display: DisplayProfilingSnapshot,
    val runtime: RuntimeProfilingSnapshot,
    val compiler: CompilerProfilingSnapshot,
    val heldEnter: HeldEnterWorkloadSummary? = null,
)

internal data class HeldEnterWorkloadSummary(
    val enterEventsQueued: Int,
    val settleTicks: Int,
    val maxQueuedEvents: Int,
    val finalQueuedEvents: Int,
    val maxPendingHostCalls: Int,
    val finalPendingHostCalls: Int,
    val displayFramesDrained: Int,
)

internal object RuntimeVmProfilingReportFormatter {
    fun markdown(
        jvm: VmRunnerProfile,
        rust: VmRunnerProfile,
    ): String =
        buildString {
            appendLine("# Runtime VM Profiling Comparison")
            appendLine()
            appendLine("Generated by `profileRuntimeVmComparison`.")
            appendLine()
            appendLine("- JVM runner: `${jvm.runnerName}`")
            appendLine("- Rust runner: `${rust.runnerName}`")
            appendLine()

            jvm.workloads.forEach { jvmWorkload ->
                val rustWorkload = rust.workloads.firstOrNull { it.name == jvmWorkload.name }
                if (rustWorkload != null) {
                    appendWorkload(jvmWorkload, rustWorkload)
                }
            }

            if (rust.workloads.any { it.runtime.instructions.isEmpty() }) {
                appendLine("## Notes")
                appendLine()
                appendLine("- Rust instruction metrics are currently unavailable, so opcode-level JVM/Rust comparisons are omitted for Rust runs.")
                appendLine("- Host-call timings may include coroutine wait time for blocking APIs such as IPC reads and event polling.")
            }
        }.trimEnd() + "\n"

    private fun StringBuilder.appendWorkload(
        jvm: RuntimeWorkloadProfile,
        rust: RuntimeWorkloadProfile,
    ) {
        appendLine("## ${jvm.name}")
        appendLine()
        appendLine("| Metric | JVM | Rust | Rust/JVM |")
        appendLine("|---|---:|---:|---:|")
        appendMetric("Display operations", jvm.display.operations.allCalls, rust.display.operations.allCalls)
        appendMetric("Display operation time", jvm.display.operations.allNanos, rust.display.operations.allNanos, ::formatNanos)
        appendMetric("Frames emitted", jvm.display.frames.frameCount, rust.display.frames.frameCount)
        appendMetric("Tiles emitted", jvm.display.frames.tileCount, rust.display.frames.tileCount)
        appendMetric("Frame build time", jvm.display.frameBuild.totalNanos, rust.display.frameBuild.totalNanos, ::formatNanos)
        appendMetric("Runtime all ticks", jvm.runtime.tick.allNanos, rust.runtime.tick.allNanos, ::formatNanos)
        appendMetric("VM execution time", jvm.runtime.vm.executionWindowNanos, rust.runtime.vm.executionWindowNanos, ::formatNanos)
        appendMetric("VM execution windows", jvm.runtime.vm.executionWindows, rust.runtime.vm.executionWindows)
        appendMetric("Host-call signals", jvm.runtime.vm.hostCallSignals, rust.runtime.vm.hostCallSignals)
        appendMetric("Host calls", jvm.runtime.hostCalls.sumOf { it.calls }, rust.runtime.hostCalls.sumOf { it.calls })
        appendMetric("Host-call time", jvm.runtime.hostCalls.sumOf { it.nanos }, rust.runtime.hostCalls.sumOf { it.nanos }, ::formatNanos)
        appendMetric("Instructions", jvm.runtime.instructions.sumOf { it.count }, rust.runtime.instructions.sumOf { it.count })
        appendMetric("Instruction time", jvm.runtime.instructions.sumOf { it.nanos }, rust.runtime.instructions.sumOf { it.nanos }, ::formatNanos)
        appendMetric("Compiler time", jvm.compiler.compileNanos, rust.compiler.compileNanos, ::formatNanos)
        appendLine()

        appendLine("### Host calls")
        appendLine()
        appendLine("| Host call | JVM calls | JVM time | Rust calls | Rust time | Rust/JVM time |")
        appendLine("|---|---:|---:|---:|---:|---:|")
        val jvmCalls = jvm.runtime.hostCalls.associateBy { it.key }
        val rustCalls = rust.runtime.hostCalls.associateBy { it.key }
        (jvmCalls.keys + rustCalls.keys).sorted().forEach { key ->
            val jvmCall = jvmCalls[key]
            val rustCall = rustCalls[key]
            appendLine(
                "| $key | ${jvmCall?.calls ?: 0} | ${formatNanos(jvmCall?.nanos ?: 0)} | " +
                    "${rustCall?.calls ?: 0} | ${formatNanos(rustCall?.nanos ?: 0)} | ${ratio(jvmCall?.nanos ?: 0, rustCall?.nanos ?: 0)} |",
            )
        }
        appendLine()

        if (jvm.heldEnter != null || rust.heldEnter != null) {
            appendLine("### Held Enter")
            appendLine()
            appendLine("| Metric | JVM | Rust | Rust/JVM |")
            appendLine("|---|---:|---:|---:|")
            appendMetric("Accepted Enter events", (jvm.heldEnter?.enterEventsQueued ?: 0).toLong(), (rust.heldEnter?.enterEventsQueued ?: 0).toLong())
            appendMetric("Final queued events", (jvm.heldEnter?.finalQueuedEvents ?: 0).toLong(), (rust.heldEnter?.finalQueuedEvents ?: 0).toLong())
            appendMetric("Max queued events", (jvm.heldEnter?.maxQueuedEvents ?: 0).toLong(), (rust.heldEnter?.maxQueuedEvents ?: 0).toLong())
            appendMetric("Frames drained", (jvm.heldEnter?.displayFramesDrained ?: 0).toLong(), (rust.heldEnter?.displayFramesDrained ?: 0).toLong())
            appendLine()
        }
    }

    private fun StringBuilder.appendMetric(
        name: String,
        jvm: Long,
        rust: Long,
        format: (Long) -> String = Long::toString,
    ) {
        appendLine("| $name | ${format(jvm)} | ${format(rust)} | ${ratio(jvm, rust)} |")
    }

    private val RuntimeHostCallMetrics.key: String get() = "$moduleName.$functionName"

    private fun ratio(
        jvm: Long,
        rust: Long,
    ): String = if (jvm <= 0) "—" else "%.2fx".format(rust.toDouble() / jvm.toDouble())

    private fun formatNanos(nanos: Long): String = "$nanos ns"
}
