pub const RAM_BASE: u32 = 0x0000_0000;

pub const PROFILE_V2_BOOT_INFO_MAGIC: u32 = u32::from_le_bytes(*b"RXBI");
pub const PROFILE_V2_VERSION: u32 = 2;
pub const PROFILE_V2_PAGE_SIZE: u32 = 256;
pub const PROFILE_V2_BOOT_INFO_ADDR: u32 = 0x0000_0000;
pub const PROFILE_V2_PROGRAM_BASE: u32 = PROFILE_V2_PAGE_SIZE;
pub const PROFILE_V2_BOOT_INFO_SIZE: u32 = 28;
pub const PROFILE_V2_HARDWARE_ENTRY_SIZE: u32 = 12;

pub const COMPUTER_HARDWARE_ID_CONTROL: u32 = 1;
pub const COMPUTER_HARDWARE_ID_DEBUG: u32 = 2;
pub const COMPUTER_HARDWARE_ID_SERIAL_INPUT: u32 = 3;
pub const COMPUTER_HARDWARE_ID_DISPLAY0: u32 = 4;
pub const COMPUTER_HARDWARE_ID_STORAGE0: u32 = 5;
pub const COMPUTER_HARDWARE_ID_FRAMEBUFFER0: u32 = 6;

pub const CONTROL_BASE: u32 = 0x1000_0000;
pub const CONTROL_STATUS: u32 = CONTROL_BASE;
pub const CONTROL_PANIC_CODE: u32 = CONTROL_BASE + 4;
pub const CONTROL_EXIT_CODE: u32 = CONTROL_BASE + 8;
pub const CONTROL_YIELD: u32 = CONTROL_BASE + 12;
pub const CONTROL_SIZE: u32 = PROFILE_V2_PAGE_SIZE;

pub const DEBUG_BASE: u32 = 0x1000_0100;
pub const DEBUG_WRITE: u32 = DEBUG_BASE;
pub const DEBUG_SIZE: u32 = PROFILE_V2_PAGE_SIZE;

pub const SERIAL_INPUT_BASE: u32 = 0x1000_0200;
pub const SERIAL_INPUT_READY: u32 = SERIAL_INPUT_BASE;
pub const SERIAL_INPUT_READ: u32 = SERIAL_INPUT_BASE + 4;
pub const SERIAL_INPUT_SIZE: u32 = PROFILE_V2_PAGE_SIZE;

pub const DISPLAY0_BASE: u32 = 0x1000_0300;
pub const DISPLAY0_COLUMNS: u32 = DISPLAY0_BASE;
pub const DISPLAY0_ROWS: u32 = DISPLAY0_BASE + 4;
pub const DISPLAY0_CURSOR_X: u32 = DISPLAY0_BASE + 8;
pub const DISPLAY0_CURSOR_Y: u32 = DISPLAY0_BASE + 12;
pub const DISPLAY0_COMMAND: u32 = DISPLAY0_BASE + 16;
pub const DISPLAY0_DATA: u32 = DISPLAY0_BASE + 20;
pub const DISPLAY0_SEQUENCE_LOW: u32 = DISPLAY0_BASE + 24;
pub const DISPLAY0_SEQUENCE_HIGH: u32 = DISPLAY0_BASE + 28;
pub const DISPLAY0_SIZE: u32 = PROFILE_V2_PAGE_SIZE;

pub const DISPLAY0_COMMAND_CLEAR: i32 = 1;
pub const DISPLAY0_COMMAND_PUT_BYTE_AT_CURSOR: i32 = 2;
pub const DISPLAY0_COMMAND_PUT_BYTE_AT_XY: i32 = 3;
pub const DISPLAY0_COMMAND_NEWLINE: i32 = 4;

pub const STORAGE0_BASE: u32 = 0x1000_0400;
pub const STORAGE0_VERSION: u32 = STORAGE0_BASE;
pub const STORAGE0_STATUS: u32 = STORAGE0_BASE + 4;
pub const STORAGE0_ERROR: u32 = STORAGE0_BASE + 8;
pub const STORAGE0_COMMAND: u32 = STORAGE0_BASE + 12;
pub const STORAGE0_BLOCK_SIZE: u32 = STORAGE0_BASE + 16;
pub const STORAGE0_CAPACITY_BLOCKS_LOW: u32 = STORAGE0_BASE + 20;
pub const STORAGE0_CAPACITY_BLOCKS_HIGH: u32 = STORAGE0_BASE + 24;
pub const STORAGE0_LBA_LOW: u32 = STORAGE0_BASE + 28;
pub const STORAGE0_LBA_HIGH: u32 = STORAGE0_BASE + 32;
pub const STORAGE0_BLOCK_COUNT: u32 = STORAGE0_BASE + 36;
pub const STORAGE0_BUFFER_ADDR: u32 = STORAGE0_BASE + 40;
pub const STORAGE0_BYTES_DONE: u32 = STORAGE0_BASE + 44;
pub const STORAGE0_SEQUENCE_LOW: u32 = STORAGE0_BASE + 48;
pub const STORAGE0_SEQUENCE_HIGH: u32 = STORAGE0_BASE + 52;
pub const STORAGE0_MEDIA_STATUS: u32 = STORAGE0_BASE + 56;
pub const STORAGE0_SIZE: u32 = PROFILE_V2_PAGE_SIZE;

pub const STORAGE_VERSION: i32 = 1;

pub const STORAGE_STATUS_READY: i32 = 0;
pub const STORAGE_STATUS_BUSY: i32 = 1;
pub const STORAGE_STATUS_DONE: i32 = 2;
pub const STORAGE_STATUS_ERROR: i32 = 3;

pub const STORAGE_ERROR_NONE: i32 = 0;
pub const STORAGE_ERROR_INVALID_COMMAND: i32 = 1;
pub const STORAGE_ERROR_MEDIA_ABSENT: i32 = 2;
pub const STORAGE_ERROR_BUFFER_OUT_OF_BOUNDS: i32 = 3;
pub const STORAGE_ERROR_LBA_OUT_OF_BOUNDS: i32 = 4;
pub const STORAGE_ERROR_BYTE_COUNT_OVERFLOW: i32 = 5;
pub const STORAGE_ERROR_WRITE_PROTECTED: i32 = 6;
pub const STORAGE_ERROR_IO_ERROR: i32 = 7;

pub const STORAGE_COMMAND_NOP: i32 = 0;
pub const STORAGE_COMMAND_READ_BLOCKS: i32 = 1;
pub const STORAGE_COMMAND_WRITE_BLOCKS: i32 = 2;
pub const STORAGE_COMMAND_FLUSH: i32 = 3;

pub const STORAGE_MEDIA_ABSENT: i32 = 0;
pub const STORAGE_MEDIA_PRESENT: i32 = 1;
pub const STORAGE_MEDIA_READ_ONLY: i32 = 2;
pub const STORAGE_MEDIA_ERROR: i32 = 3;

pub const FRAMEBUFFER0_BASE: u32 = 0x1000_0500;
pub const FRAMEBUFFER0_WIDTH: u32 = FRAMEBUFFER0_BASE;
pub const FRAMEBUFFER0_HEIGHT: u32 = FRAMEBUFFER0_BASE + 4;
pub const FRAMEBUFFER0_STRIDE_BYTES: u32 = FRAMEBUFFER0_BASE + 8;
pub const FRAMEBUFFER0_PIXEL_FORMAT: u32 = FRAMEBUFFER0_BASE + 12;
pub const FRAMEBUFFER0_COMMAND: u32 = FRAMEBUFFER0_BASE + 16;
pub const FRAMEBUFFER0_STATUS: u32 = FRAMEBUFFER0_BASE + 20;
pub const FRAMEBUFFER0_ERROR: u32 = FRAMEBUFFER0_BASE + 24;
pub const FRAMEBUFFER0_X: u32 = FRAMEBUFFER0_BASE + 28;
pub const FRAMEBUFFER0_Y: u32 = FRAMEBUFFER0_BASE + 32;
pub const FRAMEBUFFER0_RECT_WIDTH: u32 = FRAMEBUFFER0_BASE + 36;
pub const FRAMEBUFFER0_RECT_HEIGHT: u32 = FRAMEBUFFER0_BASE + 40;
pub const FRAMEBUFFER0_BUFFER_ADDR: u32 = FRAMEBUFFER0_BASE + 44;
pub const FRAMEBUFFER0_BUFFER_STRIDE_BYTES: u32 = FRAMEBUFFER0_BASE + 48;
pub const FRAMEBUFFER0_COLOR: u32 = FRAMEBUFFER0_BASE + 52;
pub const FRAMEBUFFER0_SEQUENCE_LOW: u32 = FRAMEBUFFER0_BASE + 56;
pub const FRAMEBUFFER0_SEQUENCE_HIGH: u32 = FRAMEBUFFER0_BASE + 60;
pub const FRAMEBUFFER0_SIZE: u32 = PROFILE_V2_PAGE_SIZE;

pub const FRAMEBUFFER0_PIXEL_FORMAT_RGB565: i32 = 1;

pub const FRAMEBUFFER0_STATUS_READY: i32 = 0;
pub const FRAMEBUFFER0_STATUS_DONE: i32 = 1;
pub const FRAMEBUFFER0_STATUS_ERROR: i32 = 2;

pub const FRAMEBUFFER0_ERROR_NONE: i32 = 0;
pub const FRAMEBUFFER0_ERROR_INVALID_COMMAND: i32 = 1;
pub const FRAMEBUFFER0_ERROR_BUFFER_OUT_OF_BOUNDS: i32 = 2;
pub const FRAMEBUFFER0_ERROR_INVALID_RECT: i32 = 3;
pub const FRAMEBUFFER0_ERROR_INVALID_STRIDE: i32 = 4;

pub const FRAMEBUFFER0_COMMAND_NOP: i32 = 0;
pub const FRAMEBUFFER0_COMMAND_CLEAR: i32 = 1;
pub const FRAMEBUFFER0_COMMAND_BLIT_BUFFER: i32 = 2;
pub const FRAMEBUFFER0_COMMAND_PRESENT: i32 = 3;

pub const STATUS_RESET: i32 = 0;
pub const STATUS_BOOTING: i32 = 1;
pub const STATUS_READY: i32 = 2;
pub const STATUS_HALTED: i32 = 3;
pub const STATUS_PANIC: i32 = 4;
