modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0"

[[mods]]
modId="compukters_create"
version="${addon_version}"
displayName="Compukters: Create"
displayURL="https://certifiedbadideas.github.io/Compukters/"
authors="lazyhat"
description='''Adds integration between Compukters and Create.'''

[[dependencies.compukters_create]]
modId="neoforge"
type="required"
versionRange="[21.1.250,)"
ordering="NONE"
side="BOTH"

[[dependencies.compukters_create]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.compukters_create]]
modId="compukters"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.compukters_create]]
modId="create"
type="required"
versionRange="[6.0.10,6.1)"
ordering="AFTER"
side="BOTH"
