/*
 * The Compukter Kraft Developers
 *
 * Copyright (C) 2026 Vsevolod Petrov (lazyhat)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

private const val GLYPH_WIDTH = 5
private const val GLYPH_HEIGHT = 7
private const val FALLBACK_CODEPOINT = 0xFFFD

private val requiredCodepoints =
    (0x20..0x7E).toSet() +
        setOf(0x2500, 0x2502, 0x250C, 0x2510, 0x2514, 0x2518, 0x253C, FALLBACK_CODEPOINT)

data class GeneratedK16FontTables(
    val rustSource: String,
    val kotlinSource: String,
    val markdownSpecimen: String,
)

class K16FontTableGenerator {
    fun generate(source: String): GeneratedK16FontTables {
        val glyphs = parse(source)
        validate(glyphs)
        val packed = glyphs.mapValues { (_, rows) -> pack(rows) }.toSortedMap()
        return GeneratedK16FontTables(
            rustSource = renderRust(packed),
            kotlinSource = renderKotlin(packed),
            markdownSpecimen = renderMarkdownSpecimen(glyphs.toSortedMap()),
        )
    }

    private fun parse(source: String): Map<Int, List<String>> {
        val glyphs = linkedMapOf<Int, List<String>>()
        val lines = source.lines()
        var index = 0
        while (index < lines.size) {
            val line = lines[index].trim()
            index += 1
            if (line.isEmpty() || line.startsWith("#")) continue
            require(line.startsWith("glyph ")) { "Expected `glyph U+XXXX`, got `$line` at line $index" }
            val parts = line.split(Regex("\\s+"))
            require(parts.size >= 2) { "Glyph header must include a codepoint at line $index" }
            val codepoint = parts[1].removePrefix("U+").toInt(radix = 16)
            val rows =
                (0 until GLYPH_HEIGHT).map { row ->
                    require(index < lines.size) { "Incomplete glyph U+${codepoint.hex()} at line $index" }
                    val glyphRow = lines[index].trim()
                    index += 1
                    require(glyphRow.length == GLYPH_WIDTH && glyphRow.all { it == '.' || it == '#' }) {
                        "Glyph U+${codepoint.hex()} row ${row + 1} must be $GLYPH_WIDTH cells of `.` or `#`"
                    }
                    glyphRow
                }
            glyphs[codepoint] = rows
        }
        return glyphs
    }

    private fun validate(glyphs: Map<Int, List<String>>) {
        val missing = requiredCodepoints.filterNot(glyphs::containsKey)
        require(missing.isEmpty()) {
            "Missing required glyphs: ${missing.joinToString { "U+${it.hex()}" }}"
        }
    }

    private fun pack(rows: List<String>): Long =
        rows.fold(0L) { value, row ->
            val bits =
                row.fold(0L) { rowBits, ch ->
                    (rowBits shl 1) or if (ch == '#') 1L else 0L
                }
            (value shl GLYPH_WIDTH) or bits
        }

    private fun renderRust(packed: Map<Int, Long>): String {
        val fallback = packed.getValue(FALLBACK_CODEPOINT)
        val cases =
            packed.entries.joinToString(separator = "\n") { (codepoint, glyph) ->
                "        ${rustChar(codepoint)} => 0b${glyph.bits35()},"
            }
        val knownCases =
            packed.keys.joinToString(separator = "\n") { codepoint ->
                "        ${rustChar(codepoint)} => true,"
            }
        return """
            |// Generated by ./gradlew generateK16FontTables. Do not edit by hand.
            |
            |pub const GLYPH_WIDTH: i32 = $GLYPH_WIDTH;
            |pub const GLYPH_HEIGHT: i32 = $GLYPH_HEIGHT;
            |pub const FALLBACK_GLYPH: u64 = 0b${fallback.bits35()};
            |
            |pub fn has_mono5x7_glyph(ch: char) -> bool {
            |    match ch {
            |$knownCases
            |        _ => false,
            |    }
            |}
            |
            |pub fn mono5x7_glyph(ch: char) -> u64 {
            |    match ch {
            |$cases
            |        _ => FALLBACK_GLYPH,
            |    }
            |}
            |
        """.trimMargin()
    }

    private fun renderKotlin(packed: Map<Int, Long>): String {
        val fallback = packed.getValue(FALLBACK_CODEPOINT)
        val cases =
            packed.entries.joinToString(separator = "\n") { (codepoint, glyph) ->
                "            ${codepoint.hexLiteral()}.toChar() -> 0b${glyph.bits35()}L"
            }
        val known =
            packed.keys.joinToString(separator = ", ") { codepoint ->
                "${codepoint.hexLiteral()}.toChar()"
            }
        return """
            |/*
            | * Generated by ./gradlew generateK16FontTables. Do not edit by hand.
            | */
            |package ru.lazyhat.compukterkraft.core.gui
            |
            |object GeneratedTerminalFont {
            |    const val GLYPH_WIDTH: Int = $GLYPH_WIDTH
            |    const val GLYPH_HEIGHT: Int = $GLYPH_HEIGHT
            |    const val FALLBACK_GLYPH: Long = 0b${fallback.bits35()}L
            |
            |    fun hasGlyph(ch: Char): Boolean = ch in KNOWN_GLYPHS
            |
            |    fun glyph(ch: Char): Long =
            |        when (ch) {
            |$cases
            |            else -> FALLBACK_GLYPH
            |        }
            |
            |    private val KNOWN_GLYPHS: Set<Char> = setOf($known)
            |}
            |
        """.trimMargin()
    }

    private fun renderMarkdownSpecimen(glyphs: Map<Int, List<String>>): String {
        val glyphSections =
            glyphs.entries.joinToString(separator = "\n\n") { (codepoint, rows) ->
                """
                    |## U+${codepoint.hex()} ${codepoint.displayName()}
                    |
                    |```text
                    |${rows.joinToString(separator = "\n")}
                    |```
                """.trimMargin()
            }
        return """
            |# K16 Mono 5x7 Font Specimen
            |
            |- Glyph size: ${GLYPH_WIDTH}x${GLYPH_HEIGHT}
            |- Glyph count: ${glyphs.size}
            |- Source: assets/k16/fonts/k16-mono-5x7.font
            |
            |$glyphSections
            |
        """.trimMargin()
    }

    private fun rustChar(codepoint: Int): String = "'\\u{${codepoint.toString(radix = 16)}}'"

    private fun Int.hex(): String = toString(radix = 16).uppercase().padStart(4, '0')

    private fun Int.hexLiteral(): String = "0x${hex()}"

    private fun Int.displayName(): String =
        when (this) {
            0x20 -> "SPACE"
            FALLBACK_CODEPOINT -> "FALLBACK"
            else -> String(Character.toChars(this))
        }

    private fun Long.bits35(): String = toString(radix = 2).padStart(GLYPH_WIDTH * GLYPH_HEIGHT, '0')
}
