[package]
name = "k16-bios"
version = "0.1.0"
edition = "2021"

[features]
k16-target = []

[[bin]]
name = "k16-bios"
path = "src/main.rs"
test = false
required-features = ["k16-target"]

[dependencies]
k16-abi = { path = "../k16-abi" }
k16-boot-chain = { path = "../k16-boot-chain" }
k16-rt = { path = "../k16-rt" }
