
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.21)
forge_version_range=[47.4.10,)
loader_version_range=[47]

## Mod Properties

mod_id=compukterkraft
mod_name=Compukter Kraft
mod_license=GPLv3
mod_version=1.20.1-0.0.1
mod_group_id=ru.lazyhat.compukterkraft
mod_authors=lazyhat
mod_description=Mod inspired by ComputerCraft mod, but instead of Lua - Kotlin
homepage_url=https://github.com/LazyHat/Compukter-Kraft