
#
# The Compukters Developers
#
# Copyright (C) 2026 Vsevolod Petrov (lazyhat)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Prefixes('1.21.1_', 'common_'. etc.) will be removed in properties map.
# And in mods.toml or fabric.mod.json use props without prefixes.
# needed version will be resolved automatically

# 1.21.1
1.21.1_minecraft_version=1.21.1
1.21.1_minecraft_version_range=[1.21.1]
1.21.1_neoforge_loader_version_range=[4,)
1.21.1_neoforge_mod_version_range=[21.1,)

# 1.21.11
1.21.11_minecraft_version=1.21.11
1.21.11_minecraft_version_range=[1.21.11]
1.21.11_neoforge_loader_version_range=[4,)
1.21.11_neoforge_mod_version_range=[21.11,)

## Common Mod Properties, that used by all leaf modules.

# common_mod_version - it was set by Gradle scripts, based on project version. see root gradle.properties

common_mod_id=compukters
common_mod_name=Compukters
common_mod_license=GPLv3
common_mod_group_id=ru.lazyhat.compukters
common_mod_authors=lazyhat
common_mod_description=Computers in Minecraft, programmed in Kotlin scripts with an in-game development environment.
common_homepage_url=https://github.com/CertifiedBadIdeas/Compukters
