[package]
name = "k16-ls"
version = "0.1.0"
edition = "2021"

[features]
k16-target = []

[[bin]]
name = "k16-ls"
path = "src/main.rs"
test = false
required-features = ["k16-target"]

[dependencies]
k16-abi = { path = "../k16-abi" }
kraft-std = { path = "../kraft-std" }

[dev-dependencies]
kraft-std = { path = "../kraft-std", features = ["host-test"] }
