[workspace]
members = [
    "k16-abi",
    "k16-bios",
    "k16-boot",
    "k16-boot-chain",
    "k16-image",
    "k16-init",
    "k16-shell",
    "k16-ls",
    "k16-cat",
    "k16-stat",
    "k16-write",
    "k16-rm",
    "k16-alloc-test",
    "k16-kernel",
    "k16-rt",
    "k16-storage",
    "k16-uname",
    "kraft-std",
]
resolver = "2"
