[workspace]
members = [
    "k16-abi",
    "k16-bios",
    "k16-boot",
    "k16-boot-chain",
    "k16-image",
    "k16-init",
    "k16-shell",
    "k16-shared-kraft",
    "k16-runtime-import-test",
    "k16-shared-runtime",
    "k16-alloc-test",
    "k16-proc-test",
    "k16-syscall-fault-test",
    "k16-user-fault-test",
    "k16-kernel",
    "k16-memory",
    "k16-rt",
    "k16-storage",
    "kraft-std",
]
resolver = "2"
