[package]
name = "k16-kernel"
version = "0.1.0"
edition = "2021"

[features]
host-test = ["k16-rt/host-test"]
k16-target = []

[[bin]]
name = "k16-kernel"
path = "src/main.rs"
test = false
required-features = ["k16-target"]

[dependencies]
k16-abi = { path = "../k16-abi" }
k16-rt = { path = "../k16-rt" }
